#!/usr/local/bin/ic-repl

load "common/install.sh";

//identity default;
//
//// Install the backend canister
//let arguments = record {
//  scheduler = record {
//    selection_rate = variant { SECONDS = 0 };
//    interest_duration = variant { DAYS = 1 };
//    opinion_duration = variant { SECONDS = 0 };
//    categorization_duration = variant { SECONDS = 0 };
//    rejected_duration = variant { SECONDS = 0 };
//  };
//  categories = vec {
//    "IDENTITY";
//    "COOPERATION";
//  };
//};
//
//let backend = installBackend(arguments);

// To use instead if wish to use the deployed backend
identity default "~/.config/dfx/identity/default/identity.pem";
import backend = "rrkah-fqaaa-aaaaa-aaaaq-cai";

// @todo: one should not be able to ask a question as the anonymous user "2vxsx-fae"
// @todo: find a way to test partial vec to uncomment the tests on current stage

"Create candidate questions";
call backend.createQuestions(vec {
  record { "One is not born, but rather becomes, a woman.";                                                                                              variant { INTEREST = record { interest_score = 227; } } };
  record { "Differences in treatment and quality of life in our society show that racism is still omnipresent.";                                         variant { INTEREST = record { interest_score = 202; } } };
  record { "All sciences, even chemistry and biology are not uncompromising and are conditioned by our society.";                                        variant { INTEREST = record { interest_score = 132; } } };
  record { "The categories “women” and “men” are social constructs that should be given up.";                                                            variant { INTEREST = record { interest_score = 373; } } };
  record { "Nobody is by nature predisposed to criminality.";                                                                                            variant { INTEREST = record { interest_score = 39;  } } };
  record { "Sexual orientation is a social construct";                                                                                                   variant { INTEREST = record { interest_score = 101; } } };
  record { "Social differences between ethnic groups cannot be explained by biology.";                                                                   variant { INTEREST = record { interest_score = 377; } } };
  record { "The social roles of women and men can partly be explained by biological differences.";                                                       variant { INTEREST = record { interest_score = 125; } } };
  record { "Hormonal differences can explain some differences in individual characteristics between women and men.";                                     variant { INTEREST = record { interest_score = 241; } } };
  record { "Sexual assaults are partly caused by natural impulse.";                                                                                      variant { INTEREST = record { interest_score = 365; } } };
  record { "Transgender individuals will never really be of the gender they identify as.";                                                               variant { INTEREST = record { interest_score = 244; } } };
  record { "Members of a nation or culture have some unchangeable characteristics that define them.";                                                    variant { INTEREST = record { interest_score = 345; } } };
  record { "Biologically, human beings are meant for heterosexuality.";                                                                                  variant { INTEREST = record { interest_score = 435; } } };
  record { "Selfishness is the overriding drive in the human species, no matter the context.";                                                           variant { INTEREST = record { interest_score = 497; } } };
  record { "Borders should eventually be abolished.";                                                                                                    variant { INTEREST = record { interest_score = 368; } } };
  record { "People need to stand up for their ideals, even if it leads them to betray their country.";                                                   variant { INTEREST = record { interest_score = 474; } } };
  record { "My country must pay for the damages caused by the crimes it committed in other countries.";                                                  variant { INTEREST = record { interest_score = 13;  } } };
  record { "If two countries have similar economies, social systems and environmental norms, then the free market between them has no negative impact."; variant { INTEREST = record { interest_score = 338; } } };
  record { "National Chauvinism during sports competitions is not acceptable.";                                                                          variant { INTEREST = record { interest_score = 179; } } };
  record { "I am equally concerned about the inhabitants of my country and those of other the countries.";                                               variant { INTEREST = record { interest_score = 93;  } } };
  record { "Foreigners living in my country should be allowed to act politically, equally to those who have the nationality.";                           variant { INTEREST = record { interest_score = 206; } } };
  record { "Citizens should take priority over foreigners.";                                                                                             variant { INTEREST = record { interest_score = 165; } } };
  record { "The values of my country are superior to those of other countries.";                                                                         variant { INTEREST = record { interest_score = 296; } } };
  record { "Multiculturalism is a threat to our society.";                                                                                               variant { INTEREST = record { interest_score = 213; } } };
  record { "A good citizen is a patriot.";                                                                                                               variant { INTEREST = record { interest_score = 162; } } };
  record { "It is legitimate for a country to intervene militarily to defend its economic interests.";                                                   variant { INTEREST = record { interest_score = 55;  } } };
  record { "It is necessary to teach history in order to create a sense of belonging to the nation.";                                                    variant { INTEREST = record { interest_score = 159; } } };
  record { "Research produced by my country should not be available to other countries.";                                                                variant { INTEREST = record { interest_score = 345; } } };
  record { "No one should get rich from owning a business, housing, or land.";                                                                           variant { INTEREST = record { interest_score = 51;  } } };
  record { "Wage labor is a form of theft from the worker by companies.";                                                                                variant { INTEREST = record { interest_score = 260; } } };
  record { "It is important that health should stay a public matter.";                                                                                   variant { INTEREST = record { interest_score = 230; } } };
  record { "Energy and transport structures should be a public matter.";                                                                                 variant { INTEREST = record { interest_score = 494; } } };
  record { "Patents should not exist.";                                                                                                                  variant { INTEREST = record { interest_score = 17;  } } };
  record { "It is necessary to implement assemblies to ration our production to the consumers according to their needs.";                                variant { INTEREST = record { interest_score = 481; } } };
  record { "The labor market enslaves workers.";                                                                                                         variant { INTEREST = record { interest_score = 99;  } } };
  record { "Looking for one\'s own profit is healthy for the economy.";                                                                                  variant { INTEREST = record { interest_score = 233; } } };
  record { "It is merit that explains differences of wealth between two individuals.";                                                                   variant { INTEREST = record { interest_score = 448; } } };
  record { "The fact that some schools and universities are private is not a problem.";                                                                  variant { INTEREST = record { interest_score = 31;  } } };
  record { "Offshoring and outsourcing are necessary evils to improve production.";                                                                      variant { INTEREST = record { interest_score = 125; } } };
  record { "It is acceptable that there are rich and poor people.";                                                                                      variant { INTEREST = record { interest_score = 89;  } } };
  record { "It is acceptable that some industry sectors are private.";                                                                                   variant { INTEREST = record { interest_score = 16;  } } };
  record { "Banks should remain private.";                                                                                                               variant { INTEREST = record { interest_score = 247; } } };
  record { "Revenues and capital should be taxed to redistribute wealth.";                                                                               variant { INTEREST = record { interest_score = 424; } } };
  record { "We should be retiring earlier.";                                                                                                             variant { INTEREST = record { interest_score = 93;  } } };
  record { "Dismissals of employees should be forbidden except if it is justified.";                                                                     variant { INTEREST = record { interest_score = 414; } } };
  record { "Minimal levels of salary should be ensured to make sure that a worker can live of their work.";                                              variant { INTEREST = record { interest_score = 182; } } };
  record { "It is necessary to avoid private monopoly.";                                                                                                 variant { INTEREST = record { interest_score = 467; } } };
  record { "Loans contracted by the public sector (states, regions, communities) do not necessarily have to be repaid.";                                 variant { INTEREST = record { interest_score = 484; } } };
  record { "Some sectors or type of employment should be financially supported.";                                                                        variant { INTEREST = record { interest_score = 243; } } };
  record { "Market economy is optimal when it is not regulated.";                                                                                        variant { INTEREST = record { interest_score = 296; } } };
});

"Create open opinion questions";
call backend.createQuestions(vec {
  record { "Nowadays employees are free to choose when signing a contract with their future employer";                                          variant { VOTING = variant { OPINION = record { interest_score = 74;  opinion_aggregate = record { left = 23.8812; center = 44.8296; right = 34.7636; } } } } };
  record { "It is necessary to remove regulations in labor legislation to encourage firms to hire.";                                            variant { VOTING = variant { OPINION = record { interest_score = 151; opinion_aggregate = record { left = 96.4307; center = 15.4743; right = 65.7073; } } } } };
  record { "The maximum allowed hours in the legal work week should be increased.";                                                             variant { VOTING = variant { OPINION = record { interest_score = 468; opinion_aggregate = record { left = 78.7345; center = 43.3715; right = 89.2767; } } } } };
  record { "Environmental norms should be influenced by mass consumption and not from an authority.";                                           variant { VOTING = variant { OPINION = record { interest_score = 483; opinion_aggregate = record { left = 2.3329;  center = 20.6289; right = 66.849;  } } } } };
  record { "Social assistance deters people from working.";                                                                                     variant { VOTING = variant { OPINION = record { interest_score = 97;  opinion_aggregate = record { left = 6.129;   center = 87.0397; right = 27.2682; } } } } };
  record { "State-run companies should be managed like private ones and follow the logic of the market (competition, profitability...).";       variant { VOTING = variant { OPINION = record { interest_score = 389; opinion_aggregate = record { left = 49.1467; center = 9.5908;  right = 50.5179; } } } } };
  record { "Traditions should be questioned.";                                                                                                  variant { VOTING = variant { OPINION = record { interest_score = 54;  opinion_aggregate = record { left = 36.4528; center = 34.3741; right = 12.573;  } } } } };
  record { "I do not have any problem if other official languages are added or replace the already existing official language in my country.";  variant { VOTING = variant { OPINION = record { interest_score = 157; opinion_aggregate = record { left = 54.6682; center = 3.863;   right = 76.5176; } } } } };
  record { "Marriage should be abolished.";                                                                                                     variant { VOTING = variant { OPINION = record { interest_score = 15;  opinion_aggregate = record { left = 2.6683;  center = 47.8155; right = 12.759;  } } } } };
  record { "Foreigners enrich our culture.";                                                                                                    variant { VOTING = variant { OPINION = record { interest_score = 465; opinion_aggregate = record { left = 78.3663; center = 77.9547; right = 69.3599; } } } } };
  record { "The influence of religion should decrease.";                                                                                        variant { VOTING = variant { OPINION = record { interest_score = 81;  opinion_aggregate = record { left = 95.1293; center = 71.6073; right = 60.3704; } } } } };
  record { "A language is defined by its users, not by scholars.";                                                                              variant { VOTING = variant { OPINION = record { interest_score = 412; opinion_aggregate = record { left = 70.2886; center = 85.8344; right = 37.6695; } } } } };
  record { "Euthanasia should be authorized.";                                                                                                  variant { VOTING = variant { OPINION = record { interest_score = 378; opinion_aggregate = record { left = 62.2026; center = 13.4373; right = 24.7329; } } } } };
});

"Create open categorization questions";
call backend.createQuestions(vec {
  record { "Homosexuals should not be treated equally to heterosexuals in regards to marriage, parentage, adoption or procreation."; variant { VOTING = variant { CATEGORIZATION = record { interest_score = 298; opinion_aggregate = record { left = 61.9334; center = 30.997;  right = 55.9695; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}} };
  record { "In some specific conditions the death penalty is justified.";                                                            variant { VOTING = variant { CATEGORIZATION = record { interest_score = 39;  opinion_aggregate = record { left = 94.9333; center = 43.2641; right = 79.1267; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}} };
  record { "Technological progress must not change society too quickly.";                                                            variant { VOTING = variant { CATEGORIZATION = record { interest_score = 151; opinion_aggregate = record { left = 6.0863;  center = 43.6208; right = 47.0196; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}} };
  record { "School should mostly teach our values, traditions, and fundamental knowledge.";                                          variant { VOTING = variant { CATEGORIZATION = record { interest_score = 300; opinion_aggregate = record { left = 77.1997; center = 99.3299; right = 92.7068; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}} };
  record { "Abortion should be limited to specific cases.";                                                                          variant { VOTING = variant { CATEGORIZATION = record { interest_score = 122; opinion_aggregate = record { left = 43.7304; center = 27.2591; right = 45.5462; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}} };
  record { "The main goal of a couple is to make at least one child.";                                                               variant { VOTING = variant { CATEGORIZATION = record { interest_score = 189; opinion_aggregate = record { left = 83.863;  center = 4.3951;  right = 55.0964; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}} };
  record { "Abstinence should be preferred to contraception, to preserve the true nature of the sexual act.";                        variant { VOTING = variant { CATEGORIZATION = record { interest_score = 268; opinion_aggregate = record { left = 19.4305; center = 29.4373; right = 52.0145; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}} };
  record { "It is not acceptable that human actions should lead to the extinction of species.";                                      variant { VOTING = variant { CATEGORIZATION = record { interest_score = 114; opinion_aggregate = record { left = 37.3402; center = 77.3468; right = 14.3982; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}} };
  record { "GMOs should be forbidden outside research and medical purposes.";                                                        variant { VOTING = variant { CATEGORIZATION = record { interest_score = 37;  opinion_aggregate = record { left = 52.1604; center = 80.5742; right = 87.1294; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}} };
  record { "We must fight against global warming.";                                                                                  variant { VOTING = variant { CATEGORIZATION = record { interest_score = 421; opinion_aggregate = record { left = 52.8538; center = 43.2155; right = 68.6961; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}} };
  record { "We should accept changes in our way of consuming food to limit the exploitation of nature.";                             variant { VOTING = variant { CATEGORIZATION = record { interest_score = 72;  opinion_aggregate = record { left = 88.7088; center = 17.6764; right = 41.4764; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}} };
}, variant { VOTING = variant { CATEGORIZATION } });

"Create closed questions";
call backend.createQuestions(vec {
  record { "It is important to encourage an agriculture that maintains a food biodiversity, even if the output is inferior.";                  variant { CLOSED = record { interest_score = 35 ; opinion_aggregate = record { left = 65.9404; center = 47.59  ;  right = 83.4216; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Preserving non-urban ecosystems is more important than creating jobs.";                                                            variant { CLOSED = record { interest_score = 431; opinion_aggregate = record { left = 96.42  ; center = 29.333 ;  right = 66.8053; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Reduction of waste should be done by reducing production.";                                                                        variant { CLOSED = record { interest_score = 37 ; opinion_aggregate = record { left = 93.5746; center = 39.7795;  right = 9.3433 ; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Space colonization is a good solution for supplying the lack of raw material on Earth (iron, rare metals, fuel...)";               variant { CLOSED = record { interest_score = 26 ; opinion_aggregate = record { left = 73.5391; center = 62.2683;  right = 39.8496; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Transforming ecosystems durably to increase the quality of life of human beings is legitimate.";                                   variant { CLOSED = record { interest_score = 481; opinion_aggregate = record { left = 3.5322 ; center = 94.7769;  right = 8.6613 ; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "It is necessary to massively invest in research to improve productivity.";                                                         variant { CLOSED = record { interest_score = 175; opinion_aggregate = record { left = 80.559 ; center = 43.4891;  right = 33.0047; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Transhumanism will be beneficial because it will allow us to improve our capacities.";                                             variant { CLOSED = record { interest_score = 129; opinion_aggregate = record { left = 21.671 ; center = 95.6967;  right = 86.4315; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Nuclear fission, when well maintained, is a good source of energy.";                                                               variant { CLOSED = record { interest_score = 58 ; opinion_aggregate = record { left = 45.2588; center = 47.7559;  right = 19.0761; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Exploitation of fossil fuels is necessary.";                                                                                       variant { CLOSED = record { interest_score = 81 ; opinion_aggregate = record { left = 10.1261; center = 60.7735;  right = 19.6363; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Maintaining strong economic growth should be an objective for the government.";                                                    variant { CLOSED = record { interest_score = 106; opinion_aggregate = record { left = 60.8275; center = 33.5874;  right = 5.1731 ; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Prisons should no longer exist.";                                                                                                  variant { CLOSED = record { interest_score = 474; opinion_aggregate = record { left = 91.4202; center = 10.106 ;  right = 80.1769; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "It is unfair to set a minimal penalty for an offense or a crime.";                                                                 variant { CLOSED = record { interest_score = 304; opinion_aggregate = record { left = 2.083  ; center = 38.5376;  right = 98.0652; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Individuals who get out of prison should be assisted in their reinsertion.";                                                       variant { CLOSED = record { interest_score = 474; opinion_aggregate = record { left = 23.5182; center = 77.9428;  right = 95.5742; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Justice should always take into consideration the context and the past of the condemned and adapt their penalty accordingly.";     variant { CLOSED = record { interest_score = 495; opinion_aggregate = record { left = 5.8172 ; center = 70.3442;  right = 11.472 ; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Conditions of life in jail should be greatly improved.";                                                                           variant { CLOSED = record { interest_score = 15 ; opinion_aggregate = record { left = 66.914 ; center = 49.7656;  right = 21.6142; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "The filing and storage of personal records should be delimited strictly and database cross-checking should be forbidden.";         variant { CLOSED = record { interest_score = 137; opinion_aggregate = record { left = 44.4974; center = 13.169 ;  right = 66.49  ; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "The right to be anonymous on Internet should be guaranteed.";                                                                      variant { CLOSED = record { interest_score = 412; opinion_aggregate = record { left = 99.5993; center = 55.7979;  right = 97.5312; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "The purpose of the judiciary system should be to punish those who went against the law.";                                          variant { CLOSED = record { interest_score = 108; opinion_aggregate = record { left = 72.9714; center = 17.4261;  right = 18.2264; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "The police should be armed.";                                                                                                      variant { CLOSED = record { interest_score = 475; opinion_aggregate = record { left = 70.8834; center = 29.0208;  right = 54.2627; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "The sacrifice of some civil liberties is a necessity in order to be protected from terrorist acts.";                               variant { CLOSED = record { interest_score = 83 ; opinion_aggregate = record { left = 26.5074; center = 19.6415;  right = 84.4829; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Order and authority should be respected in all circumstances.";                                                                    variant { CLOSED = record { interest_score = 460; opinion_aggregate = record { left = 80.3314; center = 55.3374;  right = 27.9926; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Heavy penalties are efficient because they are dissuasive.";                                                                       variant { CLOSED = record { interest_score = 375; opinion_aggregate = record { left = 68.2519; center = 5.7025 ;  right = 44.6903; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "It is better to arrest someone potentially dangerous preemptively rather than taking the risk of having them committing a crime."; variant { CLOSED = record { interest_score = 445; opinion_aggregate = record { left = 42.2506; center = 63.4151;  right = 77.245 ; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Mass strike is a good way to acquire new rights.";                                                                                 variant { CLOSED = record { interest_score = 77 ; opinion_aggregate = record { left = 9.3517 ; center = 47.3806;  right = 32.9425; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Armed struggle in a country is sometimes necessary.";                                                                              variant { CLOSED = record { interest_score = 206; opinion_aggregate = record { left = 83.8888; center = 79.1209;  right = 79.2338; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Insurrection is necessary to deeply change society.";                                                                              variant { CLOSED = record { interest_score = 37 ; opinion_aggregate = record { left = 91.8081; center = 58.2892;  right = 33.5035; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Activism in existing political organizations is not relevant to change society.";                                                  variant { CLOSED = record { interest_score = 17 ; opinion_aggregate = record { left = 31.2685; center = 95.4287;  right = 66.9005; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
  record { "Elections organized by the state cannot question the powers in place.";                                                            variant { CLOSED = record { interest_score = 311; opinion_aggregate = record { left = 27.1262; center = 23.552 ;  right = 5.9184 ; }; categorization_aggregate = vec { record { "IDENTITY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "COOPERATION"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "PROPERTY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "ECONOMY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CULTURE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "TECHNOLOGY"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "JUSTICE"; record { left = 0.0; center = 0.0; right = 0.0; }}; record { "CHANGE"; record { left = 0.0; center = 0.0; right = 0.0; }} }; }}};
});

"Create rejected questions";
call backend.createQuestions(vec {
  record { "Hacking has a legitimate place in political struggle.";                                             variant { REJECTED = record { interest_score = 418; } } };
  record { "Sabotage is legitimate under certain conditions.";                                                  variant { REJECTED = record { interest_score = 494; } } };
  record { "Activists must always act in strict accordance with the law.";                                      variant { REJECTED = record { interest_score = 176; } } };
  record { "Revolutions will always end up in a bad way.";                                                      variant { REJECTED = record { interest_score = 344; } } };
  record { "Changing the system radically is counter-productive. We should rather transform it progressively."; variant { REJECTED = record { interest_score = 36 ; } } };
  record { "Violence against individuals is never productive.";                                                 variant { REJECTED = record { interest_score = 83 ; } } };
  record { "We should always distance ourselves from protesters who use violence.";                             variant { REJECTED = record { interest_score = 160; } } };
  record { "We need to make compromises with the opposition to apply our ideas.";                               variant { REJECTED = record { interest_score = 427; } } };
  record { "Changes in an individual\'s way of life can induce changes in society.";                            variant { REJECTED = record { interest_score = 46 ; } } };
  record { "My religion must be spread as widely as possible.";                                                 variant { REJECTED = record { interest_score = 169; } } };
  record { "It is a small group that consciously and secretly controls the world.";                             variant { REJECTED = record { interest_score = 484; } } };
  record { "A good policy is a pragmatic policy without ideology.";                                             variant { REJECTED = record { interest_score = 428; } } };
  record { "We need to establish a monarchy to federate the people and preserve our sovereignty.";              variant { REJECTED = record { interest_score = 365; } } };
  record { "Humans should neither eat nor exploit animals.";                                                    variant { REJECTED = record { interest_score = 323; } } };
  record { "The state should be abolished.";                                                                    variant { REJECTED = record { interest_score = 319; } } };
});