[package]
name = "game"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.3.0"
ic-cdk-macros = "0.3"
serde_json = "1.0.64"
serde = "1.0.123"