name: ci

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "install wasmtime"
      run: |
       mkdir /home/runner/bin
       echo "/home/runner/bin" >> $GITHUB_PATH
       wget https://github.com/bytecodealliance/wasmtime/releases/download/v0.40.1/wasmtime-v0.40.1-x86_64-linux.tar.xz
       tar xf wasmtime-v0.40.1-x86_64-linux.tar.xz
       cp wasmtime-v0.40.1-x86_64-linux/wasmtime /home/runner/bin/wasmtime
    - name: "install vessel"
      run: |
       wget --output-document /home/runner/bin/vessel https://github.com/dfinity/vessel/releases/download/v0.6.4/vessel-linux64
       chmod +x /home/runner/bin/vessel
    - name: "install dfx"
      run: |
       DFX_VERSION=0.11.2 DFX_INSTALL_ROOT=/home/runner/bin/ sh -ci "$(curl -sSL https://internetcomputer.org/install.sh)"
       chmod +x /home/runner/bin/dfx
    - name: "install ic-repl"
      run: |
       wget --output-document /home/runner/bin/ic-repl https://github.com/chenyan2002/ic-repl/releases/download/0.3.8/ic-repl-linux64
       chmod +x /home/runner/bin/ic-repl
    - name: "check"
      run: make check-strict
    - name: "test"
      run: make test
