name: ci

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "install dfx"
      run: |
       DFX_INSTALL_ROOT=/home/runner/bin/ sh -ci "$(curl -sSL https://internetcomputer.org/install.sh)"
       chmod +x /home/runner/bin/dfx
    - name: "install nodejs"
      run: |
       curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - &&\
       apt-get install -y nodejs
    - name: "install mops"
      run: |
       npm i -g ic-mops
       mops init
    - name: "install mops test"
      run: |
       mops add test
    - name: "make"
      run: make
    - name: "test"
      run: make test
